/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddEquipmentRouteImport } from './routes/add-equipment'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as EquipmentDetailsRouteImport } from './routes/equipment-details'
import { Route as FarmerDashboardRouteImport } from './routes/farmer-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as OwnerDashboardRouteImport } from './routes/owner-dashboard'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as RegisterRouteImport } from './routes/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddEquipmentRoute = AddEquipmentRouteImport.update({
  id: '/add-equipment',
  path: '/add-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentDetailsRoute = EquipmentDetailsRouteImport.update({
  id: '/equipment-details',
  path: '/equipment-details',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/farmer-dashboard',
  path: '/farmer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner-dashboard',
  path: '/owner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/booking': typeof BookingRoute
  '/equipment-details': typeof EquipmentDetailsRoute
  '/farmer-dashboard': typeof FarmerDashboardRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/booking': typeof BookingRoute
  '/equipment-details': typeof EquipmentDetailsRoute
  '/farmer-dashboard': typeof FarmerDashboardRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/booking': typeof BookingRoute
  '/equipment-details': typeof EquipmentDetailsRoute
  '/farmer-dashboard': typeof FarmerDashboardRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-equipment'
    | '/admin-dashboard'
    | '/booking'
    | '/equipment-details'
    | '/farmer-dashboard'
    | '/login'
    | '/my-bookings'
    | '/owner-dashboard'
    | '/payment-success'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-equipment'
    | '/admin-dashboard'
    | '/booking'
    | '/equipment-details'
    | '/farmer-dashboard'
    | '/login'
    | '/my-bookings'
    | '/owner-dashboard'
    | '/payment-success'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/add-equipment'
    | '/admin-dashboard'
    | '/booking'
    | '/equipment-details'
    | '/farmer-dashboard'
    | '/login'
    | '/my-bookings'
    | '/owner-dashboard'
    | '/payment-success'
    | '/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddEquipmentRoute: typeof AddEquipmentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  BookingRoute: typeof BookingRoute
  EquipmentDetailsRoute: typeof EquipmentDetailsRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-equipment': {
      id: '/add-equipment'
      path: '/add-equipment'
      fullPath: '/add-equipment'
      preLoaderRoute: typeof AddEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment-details': {
      id: '/equipment-details'
      path: '/equipment-details'
      fullPath: '/equipment-details'
      preLoaderRoute: typeof EquipmentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer-dashboard': {
      id: '/farmer-dashboard'
      path: '/farmer-dashboard'
      fullPath: '/farmer-dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-dashboard': {
      id: '/owner-dashboard'
      path: '/owner-dashboard'
      fullPath: '/owner-dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddEquipmentRoute: AddEquipmentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BookingRoute: BookingRoute,
  EquipmentDetailsRoute: EquipmentDetailsRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
