/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddEquipmentRouteImport } from './routes/add-equipment'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EquipmentDetailsRouteImport } from './routes/equipment-details'
import { Route as FarmerDashboardRouteImport } from './routes/farmer-dashboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OwnerBookingsRouteImport } from './routes/owner-bookings'
import { Route as OwnerDashboardRouteImport } from './routes/owner-dashboard'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RevenueRouteImport } from './routes/revenue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddEquipmentRoute = AddEquipmentRouteImport.update({
  id: '/add-equipment',
  path: '/add-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentDetailsRoute = EquipmentDetailsRouteImport.update({
  id: '/equipment-details',
  path: '/equipment-details',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/farmer-dashboard',
  path: '/farmer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/owner-bookings',
  path: '/owner-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner-dashboard',
  path: '/owner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/analytics': typeof AnalyticsRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/equipment-details': typeof EquipmentDetailsRoute
  '/farmer-dashboard': typeof FarmerDashboardRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/notifications': typeof NotificationsRoute
  '/owner-bookings': typeof OwnerBookingsRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/analytics': typeof AnalyticsRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/equipment-details': typeof EquipmentDetailsRoute
  '/farmer-dashboard': typeof FarmerDashboardRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/notifications': typeof NotificationsRoute
  '/owner-bookings': typeof OwnerBookingsRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-equipment': typeof AddEquipmentRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/analytics': typeof AnalyticsRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/equipment-details': typeof EquipmentDetailsRoute
  '/farmer-dashboard': typeof FarmerDashboardRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/notifications': typeof NotificationsRoute
  '/owner-bookings': typeof OwnerBookingsRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-equipment'
    | '/admin-dashboard'
    | '/analytics'
    | '/booking'
    | '/contact'
    | '/equipment-details'
    | '/farmer-dashboard'
    | '/help'
    | '/login'
    | '/my-bookings'
    | '/notifications'
    | '/owner-bookings'
    | '/owner-dashboard'
    | '/payment-success'
    | '/payments'
    | '/profile'
    | '/register'
    | '/revenue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-equipment'
    | '/admin-dashboard'
    | '/analytics'
    | '/booking'
    | '/contact'
    | '/equipment-details'
    | '/farmer-dashboard'
    | '/help'
    | '/login'
    | '/my-bookings'
    | '/notifications'
    | '/owner-bookings'
    | '/owner-dashboard'
    | '/payment-success'
    | '/payments'
    | '/profile'
    | '/register'
    | '/revenue'
  id:
    | '__root__'
    | '/'
    | '/add-equipment'
    | '/admin-dashboard'
    | '/analytics'
    | '/booking'
    | '/contact'
    | '/equipment-details'
    | '/farmer-dashboard'
    | '/help'
    | '/login'
    | '/my-bookings'
    | '/notifications'
    | '/owner-bookings'
    | '/owner-dashboard'
    | '/payment-success'
    | '/payments'
    | '/profile'
    | '/register'
    | '/revenue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddEquipmentRoute: typeof AddEquipmentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  EquipmentDetailsRoute: typeof EquipmentDetailsRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  NotificationsRoute: typeof NotificationsRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RevenueRoute: typeof RevenueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-equipment': {
      id: '/add-equipment'
      path: '/add-equipment'
      fullPath: '/add-equipment'
      preLoaderRoute: typeof AddEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment-details': {
      id: '/equipment-details'
      path: '/equipment-details'
      fullPath: '/equipment-details'
      preLoaderRoute: typeof EquipmentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer-dashboard': {
      id: '/farmer-dashboard'
      path: '/farmer-dashboard'
      fullPath: '/farmer-dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-bookings': {
      id: '/owner-bookings'
      path: '/owner-bookings'
      fullPath: '/owner-bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-dashboard': {
      id: '/owner-dashboard'
      path: '/owner-dashboard'
      fullPath: '/owner-dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddEquipmentRoute: AddEquipmentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AnalyticsRoute: AnalyticsRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  EquipmentDetailsRoute: EquipmentDetailsRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  NotificationsRoute: NotificationsRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RevenueRoute: RevenueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
